travis:
  secure:
    BINSTAR_TOKEN: VknSbZXzChyZSVC39Y784y9gVguXhRNu03pek6/zTF5J7X4PxKmv3mBe6JC6b2zXKXBNX2Hpmxt7+jdBVRqSAIKRk1IHKKPQDkxPxn2kauulgL4OT/c6AmoTK1e0wiWPzezS3YwVQ7heARvmVTqwuk8nMeExUuJaIK5h8NpAN/bz7yARAgQEVPahyhrjO2DCWIpn0vYp0ukwm2E94jsaEhw2il89CUyxL+mox6J0F/r7XAB+a3eDcoeuAfvzpthoWYgq1auqx+VfIsjPjlBkmYfNKYpQLLCuM6P+ZcxC8lTpMYenyUHBOicDb1hytDRqYcDTiYxW3OauthwoZXfIeV2CrOIywk1uwdpInrXHhmQ/zqQO5vNb21an4x/A+h5oGt4aC6f9F8O8lKg10hWO0IMutDYaa0NR5+LlwwmI/HClNFp7F2KSB8QwjprIy6vaQuQPC563LF0dHmpBSd01w/a5sRysB+skaPV5QhR3hlOi+KmtnaZlqcRKFeE/9ZfQoI6YDRyCAHq/V3ZN+aJlLVHw/kAg0S46DTaTxNu3iispzW1ufhfWF43gfn4zDAq7ruzSqQLt08ohpWpYTZ+bI5eCWMOT/0qqgOJSfC+FyMwn7ZvtATq8SKmcx1ySZCQSNrns+xuwK8UmFD8yTGFU2y1O316Rx1mG4RVF+DFfXQg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
