travis:
  secure:
    BINSTAR_TOKEN: TyDFoeLG78sKpCrWaaPGoBlFZdCMRLHgPAmH4G8eBLYWLTImEStC34/yj3Vyg1Uwxo9NCyOme7bM45sFbAR8VpRNOsATTD/naIFD7MWq1nUIjtGPgFw7YOXGe5WN0J24nj5ZoMtcU2ujnCxNlvO9/xlPjLDvWlsS+9a5B8SlmKKCAMLR4dkSw42FOA7sw7S6UYw7YAh5COx3Xn9IoBm73Lk1yl6fQdvr520/C72zyQFIdlK9Axwv6jkhH2ZS3p64UoXaaNKIHyeE1a/KR7H+O2TkNuPHCKS40mKEUKJXOVzbmEL4yq3qYQqzHQXasPRyAmPnb7QnaJW4sms9yUe4gQomA4qcKMDPbAuwp2Tk/0apHcGQZNADm1t0jz7hpuAr+g37W2dEQVLb7/wnPcDQ0CXPLby0PNLzwK3oDU8+KgXPvkVp9diHCsbBGNT+Uy07c6P5O5kSegzRGqOfBVKzanpxe+fkyZBkcfnjcM8IZ9oGR23YM8+xNMg45fqSCeiskJAR5FuKjkPRZF4IYkakzD/5iKhtSAtVGfjR0k/KJtQJfdks9Vr4EyrFFtDmnORMLn0X6lK6CvBtTQiQlkUKGG46iNTZnxKVeHEoEWrqMXfzbpzS64yY/1y+YYe58hRbQZAJ/UVg6vxBHLCaE8dDtfZpdA9lYRTaDNBLrpfpb+E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
